routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::group(['middleware'=>'auth'], function(){


Route::resource('appoinment', 'visitor\appoinmentController');
Route::resource('doctor', 'admin\DoctorController');
Route::resource('seat', 'admin\SeatController');
Route::resource('test', 'admin\TestController');
Route::resource('package', 'admin\PackageController');
Route::resource('video', 'admin\VideoController');
Route::resource('gallery', 'admin\GalleryController');
Route::resource('Equipment', 'admin\EquipmentController');

Route::get('/admin/index','admin\OthersController@index')->name('admin');

});



Route::get('/testall','admin\TestController@visitor')->name('test.visitor');
Route::get('/packageall','admin\PackageController@visitor')->name('package.visitor');

Route::get('/seatall','admin\SeatController@visitor')->name('seat.visitor');
Route::get('/doctorall','admin\DoctorController@visitor')->name('doctor.visitor');

Route::get('/equipmentall','admin\EquipmentController@visitor')->name('equipment.visitor');

Route::get('/videoall','admin\VideoController@visitor')->name('video.visitor');
Route::get('/galleryall','admin\GalleryController@visitor')->name('gallery.visitor');
Route::get('/','admin\GalleryController@visitorhome')->name('visitor');


//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Doctor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Doctor extends Model
{
     protected $fillable=['name','email','address','specilities','designation','bd','degree','phone','schedule','image'];
}

app/Http/Controllers/admin/DoctorController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Doctor;
use Carbon\Carbon;
class DoctorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $doctor = Doctor::all();
         return view('admin.doctor.index', compact('doctor'));
    }


       public function visitor()
    {
        $doctor = Doctor::all();
         return view('visitor.doctors', compact('doctor'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('admin.doctor.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd();
         $doctor = new Doctor();

        $image = $request->file('image');
        $slug = str_slug($request->name);

        if (isset($image)) {

            $currentDate = Carbon::now()->toDateString();
            
            $image_name = $slug.'-'.$currentDate .uniqid(). '.' .$image->getClientOriginalExtension();
            if (!file_exists('image')) {
                mkdir('image', 0777, true);
            }
            $image->move('image',$image_name);
        }

        $doctor->name =$request->name;
       // $doctor->user_id = Auth::guard('dashboard')->id();
        $doctor->email =$request->email;
        $doctor->address =$request->address;
        $doctor->designation =$request->designation;
        $doctor->bd =$request->bd;
        $doctor->degree =$request->degree;      
        $doctor->specilities =$request->specilities;
        $doctor->phone =$request->phone;
        $doctor->schedule =$request->schedule;       
        $doctor->image = $image_name;
        $doctor->save();
        
        // Toastr::success('Doctor Successfully Added','message', ["positionClass" => "toast-bottom-right"]);

        return redirect()->back();  
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         {
        //$ambulance=Ambulance::where('id',auth()->id())->first();
            $doctor=doctor::where('id',$id)->first();

            // dd($ambulance);

        if ($doctor==null){

            //return 'Post Not found';
            return abort(404);
        }

        // $post=Post::where('author_id',$d)->orWhere('id',$d)->first();
        return view('admin.doctor.edit')->with('doctor',$doctor);

        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
           $doctor = doctor::findOrFail($id);

        $image = $request->file('image');
        $slug = str_slug($request->name);

        if (isset($image)) {

            $currentDate = Carbon::now()->toDateString();
            
            $image_name = $slug.'-'.$currentDate .uniqid(). '.' .$image->getClientOriginalExtension();
            
            unlink('image/'.$doctor->image);
            $image->move('image/',$image_name);

        }else{
            $image_name = $doctor->image;
        }

        $doctor->name =$request->name;
       // $doctor->user_id = Auth::guard('dashboard')->id();
        $doctor->email =$request->email;
        $doctor->address =$request->address;
        $doctor->designation =$request->designation;
        $doctor->bd =$request->bd;
        $doctor->degree =$request->degree;        
        $doctor->specilities =$request->specilities;
        $doctor->phone =$request->phone;
        $doctor->schedule =$request->schedule;       
        $doctor->image = $image_name;
        $doctor->save();
        
        // Toastr::success('Doctor Successfully Added','message', ["positionClass" => "toast-bottom-right"]);

        return redirect()->back();  
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $doctor = doctor::find($id);

        if (file_exists('image/'.$doctor->image)) {

            //unlink('image/'.$doctor->image);

        }

        $doctor->delete();

        // Toastr::success('Ambulance Successfully Deleted','message', ["positionClass" => "toast-bottom-right"]);

        return redirect()->back(); 
    }
}

resources/views/admin/doctor/create.blade.php
@extends('admin.layout.master')


@section('content')


<div style="margin-left: 190px;" class="container" style="width: 100%;">
	<h2 style="margin-left: 408px; margin-top: 80px;">Add Doctor Profile</h2>
	<hr>
	
  
 	 	<div class="row">
 	 		

 	 		<form method="post" action="{{route('doctor.store')}}" enctype="multipart/form-data">
        	
            {{csrf_field()}}
	    <div class="col-md-6">

			<div class="form-group">
				  <label for="user">Name:</label>
				  <input type="text" class="form-control" id="Name" name="name">
			</div> 

				    
		            
		    

		    <div class="form-group">
				  <label for="user">Email:</label>
				  <input type="email" class="form-control" id="Email" name="email">
			</div>

         	<div class="form-group">
				  <label for="user">Address:</label>
				  <input type="address" class="form-control" id="address" name="address">
			</div>

              

			
			<div class="form-group">
				  <label for="user">Specialities:</label>
				  <input type="text" class="form-control" id="Specilities" name="specilities">
			</div>

			<div class="form-group">
				  <label for="user">Designation:</label>
				  <input type="text" class="form-control" id="Name" name="designation">
			</div> 

			
			

			 <div class="btn-group">
         	<br>
			  <button type="submit" class="btn btn-success">Submit</button>
			  <button type="reset" class="btn btn-danger">Reset</button>
				  
		    </div>

		</div>


        
		<div class="col-md-6">



			<div class="form-group">
				  <label for="user">Birth Date:</label>
				  <input type="date" class="form-control" id="Date" name="bd">
			</div>		 	

			 <div class="form-group">
				  <label for="user">Degree:</label>
				  <input type="text" class="form-control" id="Degree" name="degree">
			</div>

			 <div class="form-group">
				  <label for="user">Phone:</label>
				  <input type="number" class="form-control" id="Degree" name="phone">
			</div>

			<div class="form-group">
				  <label for="user">Schedule:</label>
				  <input type="text" class="form-control" id="Name" name="schedule">
			</div>  

			<div class="form-group">
				  <label for="user">Image:</label>
				  <input type="file"  id="usr" value="{{old('image')}}" name="image">
			</div>   

		
			


		      
		</div>
  		
  		
		</form>

		


		</div>	

</div>			    




@stop

resources/views/admin/doctor/edit.blade.php
@extends('admin.layout.master')


@section('content')


<div style="margin-left: 190px;" class="container" style="width: 100%;">
	<h2 style="margin-left: 408px; margin-top: 80px;">Update Doctor Profile</h2>
	<hr>
	
  
 	 	<div class="row">
 	 		

 	 		<form method="post"  action="{{route('doctor.update', $doctor->id )}}" enctype="multipart/form-data">
        	{{csrf_field()}}
 			@method('put')
	    <div class="col-md-6">

			<div class="form-group">
				  <label for="user">Name:</label>
				  <input type="text" class="form-control" id="Name" value="{{$doctor->name}}" name="name">
			</div> 

				    
		            
		    

		    <div class="form-group">
				  <label for="user">Email:</label>
				  <input type="email" class="form-control" id="Email" value="{{$doctor->email}}" name="email">
			</div>

         	<div class="form-group">
				  <label for="user">Address:</label>
				  <input type="address" class="form-control" id="address" value="{{$doctor->address}}" name="address">
			</div>

              

			
			<div class="form-group">
				  <label for="user">Specilities:</label>
				  <input type="text" class="form-control" id="Specilities" value="{{$doctor->specilities}}" name="specilities">
			</div>

			<div class="form-group">
				  <label for="user">Designation:</label>
				  <input type="text" class="form-control" id="Name" value="{{$doctor->designation}}" name="designation">
			</div> 

			
			

			 <div class="btn-group">
         	<br>
			  <button type="submit" class="btn btn-success">Submit</button>
			  <button type="reset" class="btn btn-danger">Reset</button>
			  <button type="submit" class="btn btn-primary">index</button>
				  
		    </div>

		</div>


        
		<div class="col-md-6">



			<div class="form-group">
				  <label for="user">Birth Date:</label>
				  <input type="date" class="form-control" id="Date" value="{{$doctor->bd}}" name="bd">
			</div>		 	

			 <div class="form-group">
				  <label for="user">Degree:</label>
				  <input type="type" class="form-control" id="Degree" value="{{$doctor->degree}}" name="degree">
			</div>

			<div class="form-group">
				  <label for="user">Schedule:</label>
				  <input type="text" class="form-control" id="Name" value="{{$doctor->schedule}}" name="schedule">
			</div> 

			<div class="form-group">
				  <label for="user">Mobile:</label>
				  <input type="text" class="form-control" id="Name" value="{{$doctor->phone}}" name="phone">
			</div> 

			 <div class="form-group">
					<label for="user">Image:</label>
					<img style="width:100px;height:100px" src="{{ asset('image/'.$doctor->image) }}" alt="">
					 <input type="file"  id="usr" name="image">
			</div>

		
			


		      
		</div>
  		
  		
		</form>


		</div>	

</div>			    



@stop

resources/views/admin/doctor/index.blade.php
@extends('admin.layout.master')


@section('content')


<div style="margin-left: 190px;" class="container" style="width: 100%;">
  <h2 style="margin-left: 408px; margin-top: 80px;">Add Doctor Profile</h2>
  <hr>
  
  
    <div class="row">
          <div class="col-lg-12">
            <section class="panel">
              <header class="panel-heading">
                All Doctors.....
              </header>

              <table id="example1" class="table table-striped table-advance table-hover">
                <tbody>
                  <tr>
                    <th><i class="icon_profile"></i> Full Name</th>                   
                    <th><i class="icon_mail_alt"></i> Email</th>
                    <th><i class="icon_pin_alt"></i> City</th>
                    <th><i class="icon_mobile"></i> Mobile</th>
                    <th><i class="icon_mobile"></i> Specialities</th>
                    <th><i class="icon_mobile"></i> schedule</th>
                    <th><i class="icon_cogs"></i> Action</th>
                  </tr>
                  <tr>
                     @if($doctor)
                    @foreach($doctor as $doctor)
                    <td>{{ $doctor->name }}</td>                  
                    <td>{{ $doctor->email }}</td>
                    <td>{{ $doctor->address }}</td>
                    <td>{{ $doctor->phone }}</td>
                    <td>{{ $doctor->specilities }}</td>
                    <td>{{ $doctor->schedule }}</td>
                    <td>
                      <div class="btn-group">
                        <a class="btn btn-primary" href="{{ route('doctor.edit',$doctor->id) }}"><i class="icon_plus_alt2"></i></a>
 
                        <a class="btn btn-success" href="{{route('doctor.create')}}"><i class="icon_check_alt2"></i></a>

                       <form id="delete-form-{{ $doctor->id }}" action="{{ route('doctor.destroy',$doctor->id) }}" style="display: none;" method="POST">
                        {{csrf_field()}}
                        {{ method_field('DELETE') }}
                    </form>
                    <button type="button" class="btn btn-danger btn" title="Delete" onclick="if(confirm('Are you sure? You want to delete this?')){
                        event.preventDefault();
                        document.getElementById('delete-form-{{ $doctor->id }}').submit();
                    }else {
                        event.preventDefault();
                            }"><i class="icon_close_alt2"></i>
                    </button>

                      </div>
                    </td>
                  </tr>
                  @endforeach
                  @endif
                </tbody>
              </table>
            </section>
          </div>
        </div>
       </div>

@stop
@push('script')
<script type="text/javascript">
  $(function () {
    //$('#example1').DataTable();
    $('#example1').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    });
  });
</script>
@endpush