routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::group(['middleware'=>'auth'], function(){


Route::resource('appoinment', 'visitor\appoinmentController');
Route::resource('doctor', 'admin\DoctorController');
Route::resource('seat', 'admin\SeatController');
Route::resource('test', 'admin\TestController');
Route::resource('package', 'admin\PackageController');
Route::resource('video', 'admin\VideoController');
Route::resource('gallery', 'admin\GalleryController');
Route::resource('Equipment', 'admin\EquipmentController');

Route::get('/admin/index','admin\OthersController@index')->name('admin');

});



Route::get('/testall','admin\TestController@visitor')->name('test.visitor');
Route::get('/packageall','admin\PackageController@visitor')->name('package.visitor');

Route::get('/seatall','admin\SeatController@visitor')->name('seat.visitor');
Route::get('/doctorall','admin\DoctorController@visitor')->name('doctor.visitor');

Route::get('/equipmentall','admin\EquipmentController@visitor')->name('equipment.visitor');

Route::get('/videoall','admin\VideoController@visitor')->name('video.visitor');
Route::get('/galleryall','admin\GalleryController@visitor')->name('gallery.visitor');
Route::get('/','admin\GalleryController@visitorhome')->name('visitor');


//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Appoinment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Appoinment extends Model
{
    protected $fillable=['name','email','phone','gender','specialization','date','medication'];
}

app/Http/Controllers/visitor/AppoinmentController.php
<?php

namespace App\Http\Controllers\visitor;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Appoinment;
use Carbon\Carbon;
class AppoinmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $appoinment = Appoinment::all();
         return view('admin.appoinment.index', compact('appoinment'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('visitor.appoinment.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $appoinment = new Appoinment();

        $image = $request->file('image');
        $slug = str_slug($request->name);

        if (isset($image)) {

            $currentDate = Carbon::now()->toDateString();
            
            $image_name = $slug.'-'.$currentDate .uniqid(). '.' .$image->getClientOriginalExtension();
            if (!file_exists('image')) {
                mkdir('image', 0777, true);
            }
            $image->move('image',$image_name);
        }

        $appoinment->name =$request->name;
       // $doctor->user_id = Auth::guard('dashboard')->id();
        $appoinment->email =$request->email;
        $appoinment->phone =$request->phone;
        $appoinment->gender =$request->gender;
        $appoinment->specialization =$request->specialization;
        $appoinment->date =$request->date;      
        $appoinment->medication =$request->medication;
         
        $appoinment->save();
        
        // Toastr::success('Doctor Successfully Added','message', ["positionClass" => "toast-bottom-right"]);

        return redirect()->back();  
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $appoinment = appoinment::find($id);

        if (file_exists('image/'.$appoinment->image)) {

            //unlink('image/'.$doctor->image);

        }

        $appoinment->delete();

        // Toastr::success('Ambulance Successfully Deleted','message', ["positionClass" => "toast-bottom-right"]);

        return redirect()->back(); 
    }
}

resources/views/admin/appoinment/index.blade.php
@extends('admin.layout.master')


@section('content')


<div style="margin-left: 190px;" class="container" style="width: 100%;">
  <h2 style="margin-left: 408px; margin-top: 80px;">Find Latest Appoinment</h2>
  <hr>
  
  
    <div class="row">
          <div class="col-lg-12">
            <section class="panel">
              <header class="panel-heading">
                Advanced Table
              </header>

              <table class="table table-striped table-advance table-hover">
                <tbody>
                  <tr>
                    <th><i class="icon_profile"></i>Name</th>
                    <th><i class="icon_calendar"></i> Date</th>
                    <th><i class="icon_mail_alt"></i> Email</th>
                    <th><i class="icon_pin_alt"></i> Gender</th>
                    <th><i class="icon_mobile"></i> Specialization</th>
                    <th><i class="icon_mobile"></i> Phone</th>
                    <th><i class="icon_cogs"></i> Medication</th>
                     <th><i class="icon_cogs"></i>Action</th>
                  </tr>
                  <tr>
                    @if($appoinment)
                    @foreach($appoinment as $appoinment)
                    <td>{{ $appoinment->name }}</td>
                    <td>{{ $appoinment->date }}</td>
                    <td>{{ $appoinment->email }}</td>
                    <td>{{ $appoinment->gender }}</td>
                    <td>{{ $appoinment->specialization }}</td>
                    <td>{{ $appoinment->phone }}</td>
                    <td>{{ $appoinment->medication }}</td>
                    <td>
                      <div class="btn-group">
                        <a class="btn btn-primary" href="{{route('appoinment.create')}}"><i class="icon_plus_alt2"></i></a>
                        <a class="btn btn-success" href="#"><i class="icon_check_alt2"></i></a>
                          

                         <form id="delete-form-{{ $appoinment->id }}" action="{{ route('appoinment.destroy',$appoinment->id) }}" style="display: none;" method="POST">
                        {{csrf_field()}}
                        {{ method_field('DELETE') }}
                    </form>
                    <button type="button" class="btn btn-danger " title="Delete" onclick="if(confirm('Are you sure? You want to delete this?')){
                        event.preventDefault();
                        document.getElementById('delete-form-{{ $appoinment->id }}').submit();
                    }else {
                        event.preventDefault();
                            }"><i class="icon_close_alt2"></i>
                    </button>

                      </div>
                    </td>
                  </tr>
                 
                      </div>
                    </td>
                  </tr>

                   @endforeach
                  @endif
                </tbody>
              </table>
            </section>
          </div>
        </div>
        </div>

@stop