routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::group(['middleware'=>'auth'], function(){


Route::resource('appoinment', 'visitor\appoinmentController');
Route::resource('doctor', 'admin\DoctorController');
Route::resource('seat', 'admin\SeatController');
Route::resource('test', 'admin\TestController');
Route::resource('package', 'admin\PackageController');
Route::resource('video', 'admin\VideoController');
Route::resource('gallery', 'admin\GalleryController');
Route::resource('Equipment', 'admin\EquipmentController');

Route::get('/admin/index','admin\OthersController@index')->name('admin');

});



Route::get('/testall','admin\TestController@visitor')->name('test.visitor');
Route::get('/packageall','admin\PackageController@visitor')->name('package.visitor');

Route::get('/seatall','admin\SeatController@visitor')->name('seat.visitor');
Route::get('/doctorall','admin\DoctorController@visitor')->name('doctor.visitor');

Route::get('/equipmentall','admin\EquipmentController@visitor')->name('equipment.visitor');

Route::get('/videoall','admin\VideoController@visitor')->name('video.visitor');
Route::get('/galleryall','admin\GalleryController@visitor')->name('gallery.visitor');
Route::get('/','admin\GalleryController@visitorhome')->name('visitor');


//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Appoinment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Appoinment extends Model
{
    protected $fillable=['name','email','phone','gender','specialization','date','medication'];
}

app/Http/Controllers/visitor/AppoinmentController.php
<?php

namespace App\Http\Controllers\visitor;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Appoinment;
use Carbon\Carbon;
class AppoinmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $appoinment = Appoinment::all();
         return view('admin.appoinment.index', compact('appoinment'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('visitor.appoinment.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $appoinment = new Appoinment();

        $image = $request->file('image');
        $slug = str_slug($request->name);

        if (isset($image)) {

            $currentDate = Carbon::now()->toDateString();
            
            $image_name = $slug.'-'.$currentDate .uniqid(). '.' .$image->getClientOriginalExtension();
            if (!file_exists('image')) {
                mkdir('image', 0777, true);
            }
            $image->move('image',$image_name);
        }

        $appoinment->name =$request->name;
       // $doctor->user_id = Auth::guard('dashboard')->id();
        $appoinment->email =$request->email;
        $appoinment->phone =$request->phone;
        $appoinment->gender =$request->gender;
        $appoinment->specialization =$request->specialization;
        $appoinment->date =$request->date;      
        $appoinment->medication =$request->medication;
         
        $appoinment->save();
        
        // Toastr::success('Doctor Successfully Added','message', ["positionClass" => "toast-bottom-right"]);

        return redirect()->back();  
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $appoinment = appoinment::find($id);

        if (file_exists('image/'.$appoinment->image)) {

            //unlink('image/'.$doctor->image);

        }

        $appoinment->delete();

        // Toastr::success('Ambulance Successfully Deleted','message', ["positionClass" => "toast-bottom-right"]);

        return redirect()->back(); 
    }
}

resources/views/visitor/appoinment/create.blade.php
@extends('visitor.layout.master')


@section('content')

<div class="appointmentform" id="appointmentform">
<div class="container">
	<div class="register-full">
		<div class="register-right">
			<div class="register-in">
		
				<h3>APPOINTMENT FORM</h3>
				<div class=" w3_abp">
				<div class="registerimg">
					<img style="height: 500px; margin-top: -50px" 	src="{{ asset ('visitor/images/app.jpg')}}" class="img-responsive1" alt="" />
				</div>
				</div>
				<div class=" register-form">

					<form method="post" action="{{route('appoinment.store')}}" enctype="multipart/form-data">
        	
            {{csrf_field()}}
						<div class="fields-grid">
							<div class="styled-input">
								<input type="text" name="name" required=""> 
								<label>Patients Name</label>
								<span></span>
							</div> 
							<div class="styled-input">
								<input type="email" name="email" required="">
								<label>Email</label>
								<span></span>
							</div>
							<div class="styled-input">
								<input type="text" name="phone" required=""> 
								<label>Phone Number</label>
								<span></span>
							</div> 
							<div class="styled-input">
								<h2>Sex :</h2>
								  <input type="radio" name="gender" value="male"> Male
								  <input type="radio" name="gender" value="female"> Female
							</div>
							<div class="styled-input">
								<select id="category1" name="specialization" required="">

								<option name="specialization" value="">Specialization*</option>

								<option name="specialization" value="specialization">Cardiology</option>

								<option name="specialization" value="specialization">Heart Surgery</option>

								<option name="specialization" value="specialization">Skin Care</option>

								<option name="specialization" value="specialization">Body Check-up</option>

								<option name="specialization" value="specialization">Numerology</option>
								<option name="specialization" value="specialization">Diagnosis</option>
								<option name="specialization" value="specialization">Others</option>
								</select>
								<span></span>
							</div>
						
							<div class="styled-input">
							<input class="date" id="datepicker" name="date" type="text" value="MM/DD/YYYY" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'MM/DD/YYYY';}"  required="">
							</div>	
								<div class="content-wthree2">
									<div class="grid-w3layouts1">
										<div class="w3-agile1">
											<label class="rating">Taking any medications currently?<span>*</span></label>
											<ul>
												<li>
													<input type="radio" id="a-option" name="medication">
													<label for="a-option" name="medication">Yes </label>
													<div class="check"></div>
												</li>
												<li>
													<input type="radio" id="b-option" name="medication">
													<label for="b-option" name="medication">No</label>
													<div class="check"><div class="inside"></div></div>
												</li>
											</ul>
												<div class="clear"></div>
										</div>
									</div>
									<div class="clear"></div>
								</div>
								
								<input type="submit" name="submit" value="Book Appointment">
							
						</div>
						
					</form>
						
				</div>
				<div class="clearfix"></div>
			 </div>
		</div>
		</div>
	</div>
	</div>

@stop