routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::group(['middleware'=>'auth'], function(){


Route::resource('appoinment', 'visitor\appoinmentController');
Route::resource('doctor', 'admin\DoctorController');
Route::resource('seat', 'admin\SeatController');
Route::resource('test', 'admin\TestController');
Route::resource('package', 'admin\PackageController');
Route::resource('video', 'admin\VideoController');
Route::resource('gallery', 'admin\GalleryController');
Route::resource('Equipment', 'admin\EquipmentController');

Route::get('/admin/index','admin\OthersController@index')->name('admin');

});



Route::get('/testall','admin\TestController@visitor')->name('test.visitor');
Route::get('/packageall','admin\PackageController@visitor')->name('package.visitor');

Route::get('/seatall','admin\SeatController@visitor')->name('seat.visitor');
Route::get('/doctorall','admin\DoctorController@visitor')->name('doctor.visitor');

Route::get('/equipmentall','admin\EquipmentController@visitor')->name('equipment.visitor');

Route::get('/videoall','admin\VideoController@visitor')->name('video.visitor');
Route::get('/galleryall','admin\GalleryController@visitor')->name('gallery.visitor');
Route::get('/','admin\GalleryController@visitorhome')->name('visitor');


//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/room/create.blade.php
@extends('admin.layout.master')


@section('content')


<div style="margin-left: 190px;" class="container" style="width: 100%;">
	<h2 style="margin-left: 408px; margin-top: 80px;">Add Seat & Cost</h2>
	<hr>
	
  
 	 	<div class="row">
 	 		

 	 		<form method="post" action="{{route('seat.store')}}" enctype="multipart/form-data">
        	
            {{csrf_field()}}
        	

	    <div class="col-md-6">

			 <div class="form-group">
				  <label for="user">Seat Type</label>
				  <input type="text" class="form-control" id="Name" name="stype">
			</div> 

			<div class="form-group">
				  <label for="user">Total Seat</label>
				  <input type="text" class="form-control" id="Name" name="tseat">
			</div> 
	
			
			<div class="form-group">
				  <label for="user">Image:</label>
				  <input type="file"  id="usr" value="{{old('image')}}" name="image">
			</div>

			 <div class="btn-group">
         	<br>
			  <button type="submit" class="btn btn-success">Submit</button>
			  <button type="reset" class="btn btn-danger">Reset</button>
				  
		    </div>

		</div>


        
		<div class="col-md-6">

	 	

			 <div class="form-group">
				  <label for="user">Available Seat:</label>
				  <input type="text" class="form-control" id="Degree" name="aseat">
			</div>

			<div class="form-group">
				  <label for="user">Charge:</label>
				  <input type="text" class="form-control" id="Degree" name="charge">
			</div>

			 

		
			


		      
		</div>
  		
  		
		</form>

		


		</div>	

</div>			    




@stop

resources/views/admin/room/edit.blade.php
@extends('admin.layout.master')


@section('content')


<div style="margin-left: 190px;" class="container" style="width: 100%;">
	<h2 style="margin-left: 408px; margin-top: 80px;">Add Seat & Cost</h2>
	<hr>
	
  
 	 	<div class="row">
 	 		

 	 		<form method="post"  action="{{route('seat.update', $seat->id )}}" enctype="multipart/form-data">
        	
            {{csrf_field()}}
            @method('put')
        	

	    <div class="col-md-6">

			 <div class="form-group">
				  <label for="user">Seat Type</label>
				  <input type="text" class="form-control" id="Name" value="{{$seat->stype}}" name="stype">
			</div> 

			<div class="form-group">
				  <label for="user">Total Seat</label>
				  <input type="text" class="form-control" id="Name" value="{{$seat->tseat}}" name="tseat">
			</div> 
	
			 <div class="form-group">
					<label for="user">Image:</label>
					<img style="width:80px;height:80px" src="{{ asset('image/'.$seat->image) }}" alt="">
					 <input type="file"  id="usr" name="image">
			</div>

			 <div class="btn-group">
         	<br>
			  <button type="submit" class="btn btn-success">Submit</button>
			  <button type="reset" class="btn btn-danger">Reset</button>
				  
		    </div>

		</div>


        
		<div class="col-md-6">

	 	

			 <div class="form-group">
				  <label for="user">Available Seat:</label>
				  <input type="text" class="form-control" id="Degree" value="{{$seat->aseat}}" name="aseat">
			</div>

			<div class="form-group">
				  <label for="user">Charge:</label>
				  <input type="text" class="form-control" id="Degree" value="{{$seat->charge}}" name="charge">
			</div>

			 

		
			


		      
		</div>
  		
  		
		</form>

		


		</div>	

</div>			    




@stop

resources/views/admin/room/index.blade.php
@extends('admin.layout.master')


@section('content')


<div style="margin-left: 190px;" class="container" style="width: 100%;">
  <h2 style="margin-left: 408px; margin-top: 80px;">All Seat Information</h2>
  <hr>
  
  
    <div class="row">
          <div class="col-lg-12">
            <section class="panel">
              <header class="panel-heading">
                Advanced Table
              </header>

              <table class="table table-striped table-advance table-hover">
                <tbody>
                  <tr>
                    <th><i class=""></i> Room Type</th>
                    <th><i class=""></i> Total Seat</th>
                    <th><i class=""></i> Available Seat</th>
                    <th><i class=""></i> Charge</th>
                    <th><i class=""></i> Action</th>

                   
                  </tr>
                  <tr>
                     @if($seat)
                    @foreach($seat as $seat)
                    <td>{{ $seat->stype }}</td> 
                    <td>{{ $seat->tseat }}</td>
                  
                    <td>{{ $seat->aseat }}</td>
                    <td>{{ $seat->charge }}</td>
                   
                    <td>
                      <div class="btn-group">

                        <a class="btn btn-primary" href="{{ route('seat.edit',$seat->id) }}"><i class="icon_plus_alt2"></i></a>

                        <a class="btn btn-success" href="#"><i class="icon_check_alt2"></i></a>
                       
                        <form id="delete-form-{{ $seat->id }}" action="{{ route('seat.destroy',$seat->id) }}" style="display: none;" method="POST">
                        {{csrf_field()}}
                        {{ method_field('DELETE') }}
                    </form>
                    <button type="button" class="btn btn-danger " title="Delete" onclick="if(confirm('Are you sure? You want to delete this?')){
                        event.preventDefault();
                        document.getElementById('delete-form-{{ $seat->id }}').submit();
                    }else {
                        event.preventDefault();
                            }"><i class="icon_close_alt2"></i>
                    </button>

                      </div>
                    </td>
                  </tr>
                 
                      </div>
                    </td>
                  </tr>
                   @endforeach
                  @endif
                </tbody>
              </table>
            </section>
          </div>
        </div>
        </div>

@stop